/* helper macros */
#define KRFW_VULKAN_LOADER_XSTR(s2_) KRFW_VULKAN_LOADER_STR(s2_)
#define KRFW_VULKAN_LOADER_STR(s1_) #s1_

#ifdef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_DECLARE
    #ifdef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_ALREADY_DECLARED
        #error "Attempting to redeclare global functions! Make sure you haven't redefined KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    #define KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_ALREADY_DECLARED

    #define KRFW_VULKAN_LOADER_GLOBAL_FUNCTION(alias_) static PFN_vk##alias_ alias_ = nullptr;
    #define KRFW_VULKAN_LOADER_GLOBAL_FUNCTION_MANUAL(alias_) KRFW_VULKAN_LOADER_GLOBAL_FUNCTION(alias_)
#elif defined(KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_LOAD)
    #ifndef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_ALREADY_DECLARED
        #error "Global functions must already be declared using KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_DECLARE before you can load them"
    #endif

    #ifndef KRFW_VULKAN_LOADER_SCOPE
        #error "Must define KRFW_VULKAN_LOADER_SCOPE for loader to find global functions"
    #endif

    #define KRFW_VULKAN_LOADER_GLOBAL_FUNCTION(alias_) KRFW_VULKAN_LOADER_SCOPE::alias_ = reinterpret_cast<PFN_vk##alias_>(KRFW_VULKAN_LOADER_SCOPE::GetInstanceProcAddr(nullptr, "vk"KRFW_VULKAN_LOADER_XSTR(alias_)));
    #define KRFW_VULKAN_LOADER_GLOBAL_FUNCTION_MANUAL(alias_)
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE
    #ifdef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_ALREADY_DECLARED
        #error "Attempting to redeclare instance functions! Make sure you haven't redefined KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    #define KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_ALREADY_DECLARED

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME for loader to know what typename to declare as"
    #endif

    #define KRFW_VULKAN_LOADER_INSTANCE_BEGIN() struct KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME {
    #define KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(alias_) PFN_vk##alias_ alias_ = nullptr;
    #define KRFW_VULKAN_LOADER_INSTANCE_END() };
#elif defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_LOAD)
    #ifndef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_ALREADY_DECLARED
        #error "Instance functions must already be declared using KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_ALREADY_DECLARED before you can load them"
    #endif

    #ifndef KRFW_VULKAN_LOADER_SCOPE
        #error "Must define KRFW_VULKAN_LOADER_SCOPE for loader to find global functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME for loader to know what typename to define as"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE as a VkInstance to use for loading instance functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE as a struct of type KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME to use for loading instance functions"
    #endif

    #define KRFW_VULKAN_LOADER_INSTANCE_BEGIN() KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME {
    #define KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(alias_) .alias_ = reinterpret_cast<PFN_vk##alias_>(KRFW_VULKAN_LOADER_SCOPE::GetInstanceProcAddr(KRFW_VULKAN_LOADER_INSTANCE, "vk"KRFW_VULKAN_LOADER_XSTR(alias_))),
    #define KRFW_VULKAN_LOADER_INSTANCE_END() };
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE
    #ifdef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_ALREADY_DECLARED
        #error "Attempting to redeclare device functions! Make sure you haven't redefined KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    #define KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_ALREADY_DECLARED

    #ifndef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME for loader to know what typename to declare as"
    #endif

    #define KRFW_VULKAN_LOADER_DEVICE_BEGIN() struct KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME {
    #define KRFW_VULKAN_LOADER_DEVICE_FUNCTION(alias_) PFN_vk##alias_ alias_ = nullptr;
    #define KRFW_VULKAN_LOADER_DEVICE_END() };
#elif defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_LOAD)
    #ifndef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_ALREADY_DECLARED
        #error "Device functions must already be declared using KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_ALREADY_DECLARED before you can load them"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME for loader to know what typename to define as"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE
        #error "Must define KRFW_VULKAN_LOADER_DEVICE as a VkDevice to use for loading device functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE as a struct of previously defined KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME to use for loading device functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE
        #error "Must define KRFW_VULKAN_LOADER_DEVICE_STRUCTURE as a struct of type KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME to use for loading device functions"
    #endif

    #define KRFW_VULKAN_LOADER_DEVICE_BEGIN() KRFW_VULKAN_LOADER_DEVICE_STRUCTURE = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME {
    #define KRFW_VULKAN_LOADER_DEVICE_FUNCTION(alias_) .alias_ = reinterpret_cast<PFN_vk##alias_>(KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE.GetDeviceProcAddr(KRFW_VULKAN_LOADER_DEVICE, "vk"KRFW_VULKAN_LOADER_XSTR(alias_))),
    #define KRFW_VULKAN_LOADER_DEVICE_END() };
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE
    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
        #error "Attempting to redeclare instance extension functions! Make sure you haven't redefined KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_ALREADY_DECLARED

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME for loader to know what typename to declare as"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_BEGIN
    #define KRFW_VULKAN_LOADER_INSTANCE_BEGIN() struct KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME {
    #endif
    
    #ifndef KRFW_VULKAN_LOADER_INSTANCE_END
    #define KRFW_VULKAN_LOADER_INSTANCE_END() };
    #endif

    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_SUFFIX_GROUP(suffix_) struct suffix_##_T {
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_EXTENSION_GROUP(suffix_, ext_) struct ext_##_T {
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(SUFFIX_, alias_) PFN_vk##alias_##SUFFIX_ alias_ = nullptr;
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_EXTENSION_GROUP(suffix_, ext_) } ext_;
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_SUFFIX_GROUP(suffix_) } suffix_;
#elif defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_LOAD)
    #ifndef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
        #error "Instance extension functions must already be declared using KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_ALREADY_DECLARED before you can load them"
    #endif

    #ifndef KRFW_VULKAN_LOADER_SCOPE
        #error "Must define KRFW_VULKAN_LOADER_SCOPE for loader to find global functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME for loader to know what typename to define as"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE as a VkInstance to use for loading instance extension functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE as a krfw::vkf::InstanceFunctions to use for loading instance functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_BEGIN
    #define KRFW_VULKAN_LOADER_INSTANCE_BEGIN() KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME {
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_END
    #define KRFW_VULKAN_LOADER_INSTANCE_END() };
    #endif

    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_SUFFIX_GROUP(suffix_) .suffix_ = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME::suffix_##_T {
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_EXTENSION_GROUP(suffix_, ext_) .ext_ = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME::suffix_##_T::ext_##_T {
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(SUFFIX_, alias_) .alias_ = reinterpret_cast<PFN_vk##alias_##SUFFIX_>(KRFW_VULKAN_LOADER_SCOPE::GetInstanceProcAddr(KRFW_VULKAN_LOADER_INSTANCE, "vk"KRFW_VULKAN_LOADER_XSTR(alias_##SUFFIX_))),
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_EXTENSION_GROUP(suffix_, ext_) },
    #define KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_SUFFIX_GROUP(suffix_) },
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE
    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
        #error "Attempting to redeclare device extension functions! Make sure you haven't redefined KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_ALREADY_DECLARED

    #ifndef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME for loader to know what typename to declare as"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_BEGIN
    #define KRFW_VULKAN_LOADER_DEVICE_BEGIN() struct KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME {
    #endif
    
    #ifndef KRFW_VULKAN_LOADER_DEVICE_END
    #define KRFW_VULKAN_LOADER_DEVICE_END() };
    #endif

    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_SUFFIX_GROUP(suffix_) struct suffix_##_T {
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_EXTENSION_GROUP(suffix_, ext_) struct ext_##_T {
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(SUFFIX_, alias_) PFN_vk##alias_##SUFFIX_ alias_ = nullptr;
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_EXTENSION_GROUP(suffix_, ext_) } ext_;
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_SUFFIX_GROUP(suffix_) } suffix_;
#elif defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_LOAD)
    #ifndef KRFW_VULKAN_LOADER_DEVICE
        #error "Must define KRFW_VULKAN_LOADER_DEVICE as a VkDevice to use for loading device extension functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME
        #error "Must define KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME for loader to know what typename to define as"
    #endif

    #ifndef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE
        #error "Must define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE as a struct of previously defined KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME to use for loading device functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE
        #error "Must define KRFW_VULKAN_LOADER_DEVICE_STRUCTURE as a struct of type KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME to use for loading device functions"
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_BEGIN
    #define KRFW_VULKAN_LOADER_DEVICE_BEGIN() KRFW_VULKAN_LOADER_DEVICE_STRUCTURE = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME {
    #endif

    #ifndef KRFW_VULKAN_LOADER_DEVICE_END
    #define KRFW_VULKAN_LOADER_DEVICE_END() };
    #endif

    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_SUFFIX_GROUP(suffix_) .suffix_ = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME::suffix_##_T {
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_EXTENSION_GROUP(suffix_, ext_) .ext_ = KRFW_VULKAN_LOADER_SCOPE::KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME::suffix_##_T::ext_##_T {
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(SUFFIX_, alias_) .alias_ = reinterpret_cast<PFN_vk##alias_##SUFFIX_>(KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE.GetDeviceProcAddr(KRFW_VULKAN_LOADER_DEVICE, "vk"KRFW_VULKAN_LOADER_XSTR(alias_##SUFFIX_))),
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_EXTENSION_GROUP(suffix_, ext_) },
    #define KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_SUFFIX_GROUP(suffix_) },
#endif

/* global functions */
#if defined(KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_LOAD)
    KRFW_VULKAN_LOADER_GLOBAL_FUNCTION_MANUAL(GetInstanceProcAddr)
    KRFW_VULKAN_LOADER_GLOBAL_FUNCTION(EnumerateInstanceExtensionProperties)
    KRFW_VULKAN_LOADER_GLOBAL_FUNCTION(EnumerateInstanceLayerProperties)
#endif

#if defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_LOAD) || defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_LOAD)
    #if defined(KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_ALREADY_DECLARED) && (defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE))
        #error "Attempting to redeclare instance structure! Make sure you haven't redefined KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE or KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    #define KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_ALREADY_DECLARED

    KRFW_VULKAN_LOADER_INSTANCE_BEGIN()
#endif

/* instance functions */
#if defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_LOAD)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetDeviceProcAddr)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(DestroyInstance)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(EnumeratePhysicalDevices)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetPhysicalDeviceFeatures)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetPhysicalDeviceFormatProperties)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetPhysicalDeviceImageFormatProperties)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetPhysicalDeviceProperties)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetPhysicalDeviceQueueFamilyProperties)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(GetPhysicalDeviceMemoryProperties)
    KRFW_VULKAN_LOADER_INSTANCE_FUNCTION(CreateDevice)
#endif

/* instance extension functions */
#if defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_LOAD)
    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_KHR
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_SUFFIX_GROUP(khr)
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_KHR_SURFACE
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_EXTENSION_GROUP(khr, surface)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(KHR, DestroySurface)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(KHR, GetPhysicalDeviceSurfaceSupport)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(KHR, GetPhysicalDeviceSurfaceCapabilities)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(KHR, GetPhysicalDeviceSurfaceFormats)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(KHR, GetPhysicalDeviceSurfacePresentModes)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_EXTENSION_GROUP(khr, surface)

        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_KHR_SURFACE
    #endif
    
    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_KHR
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_SUFFIX_GROUP(khr)

        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_KHR
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_EXT
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_SUFFIX_GROUP(ext)
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_EXT_DEBUG_UTILS
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_EXTENSION_GROUP(ext, debug_utils)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, SetDebugUtilsObjectName)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, SetDebugUtilsObjectTag)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, QueueBeginDebugUtilsLabel)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, QueueEndDebugUtilsLabel)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, QueueInsertDebugUtilsLabel)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, CmdBeginDebugUtilsLabel)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, CmdEndDebugUtilsLabel)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, CmdInsertDebugUtilsLabel)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, CreateDebugUtilsMessenger)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, DestroyDebugUtilsMessenger)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION(EXT, SubmitDebugUtilsMessage)
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_EXTENSION_GROUP(ext, debug_utils)

        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_EXT_DEBUG_UTILS
    #endif
    
    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_EXT
        KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_SUFFIX_GROUP(ext)

        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_EXT
    #endif
#endif

#if defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_LOAD) || defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_LOAD)
    KRFW_VULKAN_LOADER_INSTANCE_END()
#endif

#if defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_LOAD) || defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_LOAD)
    #if defined(KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_ALREADY_DECLARED) && (defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE))
        #error "Attempting to redeclare instance structure! Make sure you haven't redefined KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE or KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE in the same translation unit"
    #endif
    KRFW_VULKAN_LOADER_DEVICE_BEGIN()
#endif

/* device functions */
#if defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_LOAD)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyDevice)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetDeviceQueue)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(QueueSubmit)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(QueueWaitIdle)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DeviceWaitIdle)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(AllocateMemory)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(FreeMemory)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(MapMemory)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(UnmapMemory)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(FlushMappedMemoryRanges)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(InvalidateMappedMemoryRanges)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetDeviceMemoryCommitment)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(BindBufferMemory)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(BindImageMemory)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetBufferMemoryRequirements)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetImageMemoryRequirements)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetImageSparseMemoryRequirements)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(QueueBindSparse)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateFence)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyFence)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(ResetFences)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetFenceStatus)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(WaitForFences)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateSemaphore)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroySemaphore)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateQueryPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyQueryPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetQueryPoolResults)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetImageSubresourceLayout)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateImageView)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyImageView)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateCommandPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyCommandPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(ResetCommandPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(AllocateCommandBuffers)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(FreeCommandBuffers)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(BeginCommandBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(EndCommandBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(ResetCommandBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdCopyBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdCopyImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdCopyBufferToImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdCopyImageToBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdUpdateBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdFillBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdPipelineBarrier)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBeginQuery)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdEndQuery)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdResetQueryPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdWriteTimestamp)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdCopyQueryPoolResults)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdExecuteCommands)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateEvent)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyEvent)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetEventStatus)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(SetEvent)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(ResetEvent)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateBufferView)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyBufferView)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateShaderModule)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyShaderModule)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreatePipelineCache)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyPipelineCache)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetPipelineCacheData)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(MergePipelineCaches)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateComputePipelines)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyPipeline)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreatePipelineLayout)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyPipelineLayout)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateSampler)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroySampler)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateDescriptorSetLayout)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyDescriptorSetLayout)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateDescriptorPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyDescriptorPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(ResetDescriptorPool)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(AllocateDescriptorSets)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(FreeDescriptorSets)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(UpdateDescriptorSets)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBindPipeline)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBindDescriptorSets)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdClearColorImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdDispatch)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdDispatchIndirect)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetEvent)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdResetEvent)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdWaitEvents)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdPushConstants)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateGraphicsPipelines)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateFramebuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyFramebuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CreateRenderPass)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(DestroyRenderPass)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(GetRenderAreaGranularity)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetViewport)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetScissor)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetLineWidth)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetDepthBias)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetBlendConstants)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetDepthBounds)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetStencilCompareMask)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetStencilWriteMask)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdSetStencilReference)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBindIndexBuffer)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBindVertexBuffers)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdDraw)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdDrawIndexed)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdDrawIndirect)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdDrawIndexedIndirect)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBlitImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdClearDepthStencilImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdClearAttachments)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdResolveImage)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdBeginRenderPass)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdNextSubpass)
    KRFW_VULKAN_LOADER_DEVICE_FUNCTION(CmdEndRenderPass)
#endif

/* device extension functions */
#if defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_LOAD)
    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_SUFFIX_GROUP(khr)
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR_SWAPCHAIN
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_EXTENSION_GROUP(khr, swapchain)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, CreateSwapchain)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, DestroySwapchain)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, GetSwapchainImages)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, AcquireNextImage)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, QueuePresent)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_EXTENSION_GROUP(khr, swapchain)

        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR_SWAPCHAIN
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR_DYNAMIC_RENDERING
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_EXTENSION_GROUP(khr, dynamic_rendering)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, CmdBeginRendering)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION(KHR, CmdEndRendering)
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_EXTENSION_GROUP(khr, dynamic_rendering)

        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR_DYNAMIC_RENDERING
    #endif
    
    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR
        KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_SUFFIX_GROUP(khr)

        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_KHR
    #endif
#endif

#if defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_LOAD) || defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE) || defined(KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_LOAD)
    KRFW_VULKAN_LOADER_DEVICE_END()
#endif

/* cleanup */
#ifdef KRFW_VULKAN_LOADER_SCOPE
    #undef KRFW_VULKAN_LOADER_SCOPE
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE
    #undef KRFW_VULKAN_LOADER_INSTANCE
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE
    #undef KRFW_VULKAN_LOADER_DEVICE
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE
    #undef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE
    #undef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME
    #undef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_TYPE_NAME
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME
    #undef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_TYPE_NAME
#endif

#ifdef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_DECLARE
    #undef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_DECLARE
#endif

#ifdef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_LOAD
    #undef KRFW_VULKAN_LOADER_GLOBAL_FUNCTIONS_LOAD
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE
    #undef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_DECLARE
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_LOAD
    #undef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_LOAD
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE
    #undef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_DECLARE
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_LOAD
    #undef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_LOAD
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE
    #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_DECLARE
#endif

#ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_LOAD
    #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_LOAD
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE
    #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_DECLARE
#endif

#ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_LOAD
    #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_LOAD
#endif

#if !defined(KRFW_VULKAN_LOADER_POLLUTE_TU) || defined(KRFW_VULKAN_LOADER_FORCE_CLEAN)
    #ifdef KRFW_VULKAN_LOADER_FORCE_CLEAN
        #ifdef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_ALREADY_DECLARED
            #undef KRFW_VULKAN_LOADER_INSTANCE_STRUCTURE_ALREADY_DECLARED
        #endif

        #ifdef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_ALREADY_DECLARED
            #undef KRFW_VULKAN_LOADER_DEVICE_STRUCTURE_ALREADY_DECLARED
        #endif

        #ifdef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_ALREADY_DECLARED
            #undef KRFW_VULKAN_LOADER_INSTANCE_FUNCTIONS_ALREADY_DECLARED
        #endif

        #ifdef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_ALREADY_DECLARED
            #undef KRFW_VULKAN_LOADER_DEVICE_FUNCTIONS_ALREADY_DECLARED
        #endif

        #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
            #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
        #endif

        #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
            #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTIONS_ALREADY_DECLARED
        #endif

        #undef KRFW_VULKAN_LOADER_FORCE_CLEAN
    #endif

    #ifdef KRFW_VULKAN_LOADER_GLOBAL_FUNCTION
        #undef KRFW_VULKAN_LOADER_GLOBAL_FUNCTION
    #endif

    #ifdef KRFW_VULKAN_LOADER_GLOBAL_FUNCTION_MANUAL
        #undef KRFW_VULKAN_LOADER_GLOBAL_FUNCTION_MANUAL
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_BEGIN
        #undef KRFW_VULKAN_LOADER_INSTANCE_BEGIN
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_FUNCTION
        #undef KRFW_VULKAN_LOADER_INSTANCE_FUNCTION
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_END
        #undef KRFW_VULKAN_LOADER_INSTANCE_END
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_BEGIN
        #undef KRFW_VULKAN_LOADER_DEVICE_BEGIN
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_FUNCTION
        #undef KRFW_VULKAN_LOADER_DEVICE_FUNCTION
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_END
        #undef KRFW_VULKAN_LOADER_DEVICE_END
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_SUFFIX_GROUP
        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_SUFFIX_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_EXTENSION_GROUP
        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_BEGIN_EXTENSION_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION
        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_FUNCTION
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_EXTENSION_GROUP
        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_EXTENSION_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_SUFFIX_GROUP
        #undef KRFW_VULKAN_LOADER_INSTANCE_EXTENSION_END_SUFFIX_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_SUFFIX_GROUP
        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_SUFFIX_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_EXTENSION_GROUP
        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_BEGIN_EXTENSION_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION
        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_FUNCTION
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_EXTENSION_GROUP
        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_EXTENSION_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_SUFFIX_GROUP
        #undef KRFW_VULKAN_LOADER_DEVICE_EXTENSION_END_SUFFIX_GROUP
    #endif

    #ifdef KRFW_VULKAN_LOADER_STR
        #undef KRFW_VULKAN_LOADER_STR
    #endif

    #ifdef KRFW_VULKAN_LOADER_XSTR
        #undef KRFW_VULKAN_LOADER_XSTR
    #endif
#elif defined(KRFW_VULKAN_LOADER_POLLUTE_TU)
    #undef KRFW_VULKAN_LOADER_POLLUTE_TU
#endif