name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, freebsd-latest, openbsd-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unix and Unix-likes
        if: runner.os != 'Windows'
        run: sh build.sh release
      - name: Windows
        if: runner.os == 'Windows'
        run: build.bat release
